name: Kernel Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
