name: run-windows

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Set Password for runneradmin
        shell: powershell
        run: |
          net user runneradmin "Password123!"

      - name: Enable RDP
        shell: powershell
        run: |
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0
          Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -Name "UserAuthentication" -Value 1

      - name: Tailscale Kurulumu ve Bağlantı
        uses: tailscale/github-action@v2
        with:
          authkey: ${{ secrets.TAILSCALE_AUTHKEY }}
          version: latest

      - name: Oturumu Açık Tutma ve Tailscale Keep-Alive
        shell: pwsh
        run: |
          Write-Host "Runner aktif. Telefonunuzdaki Microsoft Remote Desktop uygulaması ile Tailscale IP adresine bağlanabilirsiniz."
          while ($true) {
              & "C:\Program Files\Tailscale\tailscale.exe" status | Out-Null
              Start-Sleep -Seconds 20
          }
