name: macOS Tailscale Simple

on:
  workflow_dispatch:

jobs:
  run-macos:
    runs-on: macos-latest
    timeout-minutes: 360

    steps:
      - name: Ekran Paylaşımını (VNC) Etkinleştir
        run: |
          sudo launchctl load -w /System/Library/LaunchDaemons/com.apple.screensharing.plist
          sudo defaults write /Library/Preferences/com.apple.AppleVNCServer VNCAuthentication -int 1
          sudo defaults write /Library/Preferences/com.apple.AppleVNCServer Password -string "password123"
          sudo /System/Library/CoreServices/RemoteManagement/ARDAgent.app/Contents/Resources/kickstart -activate -configure -access -on -users admin -privs -all -restart -agent -menu

      - name: Tailscale CLI Kurulumu ve Bağlantı
        run: |
          brew install tailscale
          sudo tailscaled &
          sleep 3
          sudo tailscale up --authkey="${{ secrets.TAILSCALE_AUTHKEY }}" --accept-routes

      - name: Oturumu Açık Tutma
        run: |
          echo "macOS runner aktif."
          while true; do
              tailscale status > /dev/null
              sleep 20
          done
          
