name: Windows RDP Session

on:
  workflow_dispatch:

jobs:
  run-windows:
    runs-on: windows-latest
    timeout-minutes: 360

    steps:
      - name: Şifre Politikasını Devre Dışı Bırak ve Kullanıcı Oluştur
        run: |
          secedit /export /cfg C:\secpol.cfg
          (Get-Content C:\secpol.cfg).replace("PasswordComplexity = 1", "PasswordComplexity = 0") | Set-Content C:\secpol.cfg
          secedit /configure /db C:\windows\security\database\secpol.sdb /cfg C:\secpol.cfg /areas SECURITYPOLICY
          gpupdate /force

          net user siksiken siksiken /add
          net localgroup administrators siksiken /add
          net accounts /maxpwage:unlimited

      - name: RDP Servisini Etkinleştir
        run: |
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0
          Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -Name "UserAuthentication" -Value 1

      - name: Winget ile Tailscale Kurulumu ve Bağlantı
        run: |
          # Winget onay ekranlarına takılmadan direkt kurar
          winget install --id Tailscale.Tailscale --silent --accept-source-agreements --accept-package-agreements
          
          # Komut satırı yolunun güncellenmesi için kısa bir bekleme
          Start-Sleep -Seconds 10
          
          & "C:\Program Files\Tailscale\tailscale.exe" up --authkey="${{ secrets.TAILSCALE_AUTHKEY }}" --accept-routes
          
          $tsIp = (& "C:\Program Files\Tailscale\tailscale.exe" ip -4)
          Write-Output "=================================================="
          Write-Output "TAILSCALE IP ADRESİNİZ (RDP için): $tsIp"
          Write-Output "=================================================="

      - name: Oturumu Açık Tutma
        run: |
          while ($true) {
              Start-Sleep -Seconds 20
          }
