name: NoMachine XFCE Direct SSH Tunnel

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 360

    steps:
      - name: Runner Hazırlığı
        uses: actions/checkout@v4

      - name: Sistem Güncelleme ve XFCE Kurulumu
        run: |
          sudo apt-get update
          sudo DEBIAN_FRONTEND=noninteractive apt-get install -y \
            xfce4 \
            xfce4-goodies \
            dbus-x11 \
            curl \
            net-tools

      - name: NoMachine İndir ve Kur
        run: |
          curl -fSL "https://web9001.nomachine.com/download/9.8/Linux/nomachine_9.8.2_1_amd64.deb" -o nomachine.deb
          sudo dpkg -i nomachine.deb
          sudo apt-get install -f -y

      - name: Kullanıcı Şifresi Ayarla
        run: |
          echo "runner:sifre123" | sudo chpasswd
          echo "Kullanıcı adı: runner"
          echo "Şifre: sifre123"

      - name: GitHub Actions SSH Servisini Aktif Et
        uses: mxschmitt/action-tmate@v3
        with:
          limit-access-to-actor: false

      - name: Oturumu Açık Tut
        run: |
          echo "NoMachine 4000 portu aktif."
          sleep i
          nfinity
